### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [200]:
%matplotlib notebook

In [254]:
# Dependencies and Setup


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# File to Load (Remember to Change These)
purchase_data = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data_df = pd.read_csv("Resources/purchase_data.csv")
purchase_data_df
#purchase_data_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

## Player Count

* Display the total number of players

In [255]:
Unique_players_df = pd.DataFrame({'Total Players': [total_players]})
Unique_players_df

   Total Players
0            576

## Purchasing Analysis (Total)

In [236]:
#how many unique items are there?
unique_items = purchase_data_df['Item ID'].nunique()
unique_items

183

In [205]:
#purchase count
purchase_count = purchase_data_df["Purchase ID"].count()
purchase_count

780

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting



* Display the summary data frame

In [206]:
Avg_price = purchase_data_df["Price"].mean()
Avg_price

3.050987179487176

In [104]:
Avg_price = round((Avg_price),2)
Avg_price

3.05

In [207]:
Total_Revenue = purchase_data_df["Price"].sum()
Total_Revenue

2379.77

In [208]:
Summary_df = pd.DataFrame({'Number of Unique Items': [unique_items],'Average Price': [Avg_price],'Number of Purchases': [purchase_count],'Total Revenue': [Total_Revenue]})
Summary_df

   Number of Unique Items  Average Price  Number of Purchases  Total Revenue
0                     183       3.050987                  780        2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [210]:
fem_players = gender_df.loc[gender_df["Gender"] == "Female"]
male_players = gender_df.loc[gender_df["Gender"] == "Male"]
other_players = gender_df.loc[(gender_df["Gender"] != "Male") & (gender_df["Gender"] != "Female")]
#fem_players.head()
#male_players.head()
other_players

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
82,82,Haerithp41,16,Other / Non-Disclosed,160,Azurewrath,4.40
111,111,Sundim98,21,Other / Non-Disclosed,41,Orbit,4.75
228,228,Jiskirran77,20,Other / Non-Disclosed,80,Dreamsong,3.39
237,237,Idairin51,20,Other / Non-Disclosed,16,Restored Bauble,3.55
242,242,Eodaisu60,16,Other / Non-Disclosed,39,"Betrayal, Whisper of Grieving Widows",3.94
350,350,Rairith81,15,Other / Non-Disclosed,34,Retribution Axe,2.22
401,401,Lirtim36,15,Other / Non-Disclosed,46,Hopeless Ebon Dualblade,1.33
549,549,Maluncil97,25,Other / Non-Disclosed,146,Warped Iron Scimitar,3.10
637,637,Airi27,24,Other / Non-Disclosed,163,Thunderfury Scimitar,3.45

In [211]:

fem = gender_df.loc[gender_df["Gender"] == "Female"]
male = gender_df.loc[gender_df["Gender"] == "Male"]
other = gender_df.loc[(gender_df["Gender"] != "Male") & (gender_df["Gender"] != "Female")]
total = len(male) + len(fem) + len(other)
data = {"Total Players":[len(male),len(fem),len(other)],
        "Percentage of Players":[round(len(male)/total*100,2),round(len(fem)/total*100,2),round(len(other)/total*100,2)]}
gender_demo_df = pd.DataFrame(data, index=["Male","Female","Other / Non-Disclosed"])
gender_demo_df

                       Total Players  Percentage of Players
Male                             484                  84.03
Female                            81                  14.06
Other / Non-Disclosed             11                   1.91


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [212]:
gender_pur_tot = purchase_data_df.groupby(['Gender']).sum()["Price"].rename("Purchase Total")
gender_avg = purchase_data_df.groupby(["Gender"]).mean()["Price"].rename("Average Purchase Price")
gender_counts = purchase_data_df.groupby(["Gender"]).count()["Price"].rename("Purchase Count")
Avg_puch_per_player = (gender_pur_tot//gender_counts.rename("Total Count"))
gender_data = pd.DataFrame({"Purchase Count": gender_counts, "Average Purchase Price": gender_avg, "Purchase Total": gender_pur_tot})
gender_data

                       Purchase Count  Average Purchase Price  Purchase Total
Gender
Female                            113                3.203009          361.94
Male                              652                3.017853         1967.64
Other / Non-Disclosed              15                3.346000           50.19

In [ ]:
#OBSERVABLE TRENDS:
    
    Male players are more likely to purchase the available games than both
    females and those claiming an alternate gender or not disclosing a gender.
    The games chosen by male players on the average tend to be less expensive 
    than games chosen by non-male players.

## Age Demographics

In [265]:
purchase_data_df.drop_duplicates('SN')

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Ranges
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40 +
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,40 +
24,24,Siala43,30,Male,141,Persuasion,3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
728,728,Chanosiaya39,44,Male,93,Apocalyptic Battlescythe,1.97,40 +
729,729,Assylla81,20,Male,74,Yearning Crusher,4.18,20-24
730,730,Aidaira26,30,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,30-34
731,731,Eudanu84,22,Female,12,Dawne,1.02,20-24
733,733,Chamiman85,20,Male,66,Victor Iron Spikes,4.40,20-24
736,736,Tyialisti80,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
737,737,Marundi65,22,Male,149,"Tranquility, Razor of Black Magic",1.75,20-24
738,738,Eusur90,36,Male,121,Massacre,1.60,35-39
739,739,Mindirranya33,35,Male,61,Ragnarok,3.87,35-39
741,741,Phiallylis33,19,Male,145,Fiery Glass Crusader,4.58,15-19
742,742,Isty55,20,Male,5,Putrid Fan,4.08,20-24
743,743,Frichilsa31,15,Male,110,Suspension,1.44,15-19
745,745,Chanista95,39,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,35-39
746,746,Aellyria80,23,Male,159,"Oathbreaker, Spellblade of Trials",3.08,20-24
748,748,Rastynusuir31,20,Male,55,Vindictive Glass Edge,2.27,20-24
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40 +
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,15-19
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,4.19,<10

In [266]:
#Assign data to bins

bins = [0,9.9,14.9,19.9,24.9,29.9,34.9,39.9,np.inf]
labels = ["<10","10-14","15-19","20-24","25-29","30-34","35-39","40 +"]

In [260]:
purchase_data_df.dtypes

Purchase ID       int64
SN               object
Age               int64
Gender           object
Item ID           int64
Item Name        object
Price           float64
Age Ranges     category
dtype: object

In [268]:
#Calculate values

purchase_data_df["Age Ranges"] = pd.cut(purchase_data_df["Age"], bins, labels=labels)
players_group = purchase_data_df.groupby("Age Ranges")
players_count = players_group["Age"].count()
percent_players = (players_count/len(gender_df)*100).astype(float).map('{:.2f}'.format)
age_demo = pd.DataFrame({"Total Count":players_count,"Percentage of Players":percent_players})
age_demo

            Total Count Percentage of Players
Age Ranges
<10                  23                  3.99
10-14                28                  4.86
15-19               136                 23.61
20-24               365                 63.37
25-29               101                 17.53
30-34                73                 12.67
35-39                41                  7.12
40 +                 13                  2.26

In [ ]:
#OBSERVABLE TRENDS:
    The games available for purchase are most popular with people from 15 years
    old through 24 years old; generally those of high school and college ages.
    Sixty-three percent of all players are college age players. The number of 
    college aged players is more than 20% higher than the two closest age categories
    combined.

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [298]:
purchase_data_df["Age Group"] = pd.cut(purchase_data_df["Age"],bins=bins,labels=labels)
buyer_group = purchase_data_df.groupby("Age Group")
buyer_count = buyer_group["Age"].count()
buyer_total = buyer_group["Price"].sum().astype(float)
buyer_avg = (buyer_total/buyer_count).astype(float)
perbuyer_avg = (buyer_total/players_count).astype(float)

demo = {"Purchase Count":buyer_count,"Average Purchase Price":buyer_avg,"Total Purchase Value":buyer_total.astype(float),"Average Total Purch. Per Buyer":perbuyer_avg}
#.map('${:,.2f}').format
demo_df = pd.DataFrame(demo)
demo_df

,Purchase Count,Average Purchase Price,Total Purchase Value,Average Total Purch. Per Buyer
Age Group,,,,
<10,23,3.353478,77.13,3.353478
10-14,28,2.956429,82.78,2.956429
15-19,136,3.035956,412.89,3.035956
20-24,365,3.052219,1114.06,3.052219
25-29,101,2.900990,293.00,2.900990
30-34,73,2.931507,214.00,2.931507
35-39,41,3.601707,147.67,3.601707
40 +,13,2.941538,38.24,2.941538

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [281]:
big_spender_count_df = purchase_data_df.groupby("SN").count()["Price"].rename("Purchase Count")
big_spender_avgprice_df = purchase_data_df.groupby("SN").mean()["Price"].rename("Average Purchase Price")
big_spender_total_df = purchase_data_df.groupby("SN").sum()["Price"].rename("Total Purchase Value")

big_spender_demo_df = pd.DataFrame({"Purchase Count":big_spender_count_df,
                                   "Average Purchase Price":big_spender_avgprice_df,
                                   "Total Purchase Value":big_spender_total_df})
#big_spender_demo_df.head()
topbig_spender_df = big_spender_demo_df.sort_values("Total Purchase Value", ascending=False)
topbig_spender_df.head()

             Purchase Count  Average Purchase Price  Total Purchase Value
SN
Lisosia93                 5                3.792000                 18.96
Idastidru52               4                3.862500                 15.45
Chamjask73                3                4.610000                 13.83
Iral74                    4                3.405000                 13.62
Iskadarya95               3                4.366667                 13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [294]:
items_count_df = purchase_data_df.groupby(["Item ID", "Item Name"]).count()["Price"].rename("Number of Purchases")
avg_items_price_df = purchase_data_df.groupby(["Item ID", "Item Name"]).mean()["Price"].rename("Average Purchase Price")
total_items_value_df = purchase_data_df.groupby(["Item ID","Item Name"]).sum()["Price"].rename("Total Value of Purchase")
topitems_df = pd.DataFrame({"Number of Purchases":items_count_df,
                            "Average Purchase Price":avg_items_price_df,
                            "Total Value of Purchase":total_items_value_df})
#topitems_df

In [293]:
topitems_sorted_df = topitems_df.sort_values("Number of Purchases", ascending=False)
topitems_sorted_df.head()

,,Number of Purchases,Average Purchase Price,Total Value of Purchase
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
145,Fiery Glass Crusader,9,4.58,41.22
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
82,Nirvana,9,4.90,44.10
19,"Pursuit, Cudgel of Necromancy",8,1.02,8.16

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [295]:
profits_df = topitems_df.sort_values("Total Value of Purchase", ascending=False)
profits_df.head()

,,Number of Purchases,Average Purchase Price,Total Value of Purchase
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
82,Nirvana,9,4.90,44.10
145,Fiery Glass Crusader,9,4.58,41.22
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80

In [ ]:
#OBSERVABLE TRENDS
    The best selling game among the available games appears to be "Oathbreaker, 
    Last Hope of the Breaking Storm". The purchase data suggests that while it is 
    the most popular, it is not the cheapest game available. When making choices 
    between available titles, there does not appear to be a clear correlation
    of popularity and price. The second most popular game is more expensive than 
    the first, but far more expensive than a host of games that sold less copies.